language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: ZuRveS4yXgFQK2qd9ecsuinTmkehjwTw/jrHajiodn1GpyaK4UxJLiPIX8dmtXC5CtryiK7oQef57utk/3CBeXSkbWNwu4BRB2vV3UddjHSMtwHF3AUstc9dORLAxUaehzNi52QyEdlA0Ij2jktlMOvo4AS65ZCBxWDwM7URnE9zDgvYi1DUBycQHopHp8v9xPKtB6MdWMRyH16Py5sSZcIntojpYTPYLP4NmwfHLZHJmXrXd9E+uA6MQg+PV26P57mUpos20j+Oxkr9MdZioyOQ3Pnkv0e6WO76UBUC035yEoSzTuExO1t3YNnPHD6L0oSHwYvUDa2tALQ7TmyUB4Dd5XCR9yz2HqdxlqLhsXca0Bn7498mMTKsh8JsT1N5bpJev2+YeJGuwqhY0unmf6hH3c/vhUwysKF4kzY0sF1NqzJf+f2B/yu9aXQlTIS+l+MqUNruZbJRQYYIeIY6SH1bnRqi/EZFeDhNh+3Yic+gm8H5N04M2Uvec+ZNULftCxbSlWXD7f772DhF7AuAWgEgLmgUIdzD1z9vwHs2IuPeUQb+cAD5a8dYVnFeDDrPSYVJDhlNbD0wtxCWBCIBiIZgUAUznZtppqrNtm3ftHxFwiw/WsAFsidYEijiCpVO76vvsVQiiS2O4mVVnQt7OzwGBbW1J+oTtcRDnnWXrj0=
  app: kitchensinkcjs
  skip-cleanup: true
