language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: QKu77yOHWfN0CPhwaPzdQpTmZUSQG2Jb36pLdn57Sm2LixwgBao7yPErM/m8tZCoqJsBUA21MANdHrCmbZ5Yh+itw7PiTNdP1ISNzKQiGNHpwOvU0kE2In5F7leD3VJY+LxUQRkUzmSglVUlxgLqjOTsq9pP86960cCrJsFl3AjwcpSz4twk8qCc+E1yM1Uuu6tdqjw+HUsKzmvaQqdf1Ypo/YZsvDzaiHSOcsDDrLltu6ZgQoz7m6uVaJISGO/MYdNR+HJw1CHkzI5Kdt/9S7cqTHOLifdf4niKkqf73Ph7JybViDoxSOpSJGezfiXOAcKNdHU4tsFNhud4U9hDNAIWVq5vdVIaKuAsI5i37ABlL1yhlkrYaCAlJdq6KIw38DaSu7W9zCjsSoefwhEsKipZh+xQCGDlt2j4DiHIYftTmudA/ODDuiQLbFmYhKFR3nLJZk6BkL8TUxfFX1CInI7h2NPCZwWn6f84FrWBshphZmV+BWxHAtWJZrcDEZuD+NiInhmzhGbrfpG+OsWrJjo4Foi2fi7V4wkpV7Ly01zyXUP4VjGh6aiSTYUIi5nfH75BQIeq5Uo7NrntlOlbdox+2TQ8D3Zu5FKzv+2GSVr5uD7imRya7N/gojUHniiz2x4jyvCtNGx/JWsdMpbxFxVhYAG1qs71agPmse0n99A=
  app: kitchensinkcjs
  skip-cleanup: true
